/**
 * proyectos.js — RobotikSD
 * Renders projects, videos, images and PDFs from JSON data files
 * generated by Decap CMS from Markdown front-matter.
 *
 * DATA FLOW:
 *   Decap CMS → saves .md files in content/proyectos/
 *   A build step (or netlify plugin) compiles them to data/*.json
 *   This JS reads the JSON and builds the UI
 *
 * FOR LOCAL / GITHUB PAGES (no build tool):
 *   Edit js/data.js manually OR use the CMS which auto-generates it.
 */

// ─── CONFIG ─────────────────────────────────────────────────────────────────
const DATA_URL    = 'js/data.json';   // Auto-generated from CMS content
const YOUTUBE_NOCOOKIE = 'https://www.youtube-nocookie.com/embed/';

// ─── STATE ──────────────────────────────────────────────────────────────────
let allProjects = [];
let allVideos   = [];
let allImages   = [];
let allPDFs     = [];
let activeFilter = 'all';

// ─── BOOTSTRAP ──────────────────────────────────────────────────────────────
document.addEventListener('DOMContentLoaded', async () => {
  await loadData();
  initFilters();
  initMediaTabs();
  initLightbox();
  renderAll();
  updateStats();
});

// ─── DATA LOADING ───────────────────────────────────────────────────────────
async function loadData() {
  try {
    const res  = await fetch(DATA_URL + '?t=' + Date.now());
    const data = await res.json();
    allProjects = data.projects  || [];
    allVideos   = data.videos    || [];
    allImages   = data.images    || [];
    allPDFs     = data.pdfs      || [];
  } catch (e) {
    console.warn('No data.json found — using sample data.', e);
    loadSampleData();
  }
}

function loadSampleData() {
  allProjects = [
    {
      id: 'robot-seguidor',
      title: 'Robot Seguidor de Línea',
      category: 'robotica',
      description: 'Construimos un robot autónomo capaz de seguir una línea negra usando sensores de infrarrojos y programación por bloques en mBlock.',
      image: '',
      emoji: '🤖',
      gradient: 'linear-gradient(135deg, #1565c0 0%, #00bcd4 100%)',
      tags: ['Lego EV3', 'mBlock', 'Sensores IR'],
      hasVideo: true,
      hasPDF: false,
      date: '2025-03',
      course: 'Nivel 3 · PAI 8-9'
    },
    {
      id: 'juego-scratch',
      title: 'Videojuego Plataformas Scratch',
      category: 'scratch',
      description: 'Diseño y programación completa de un videojuego de plataformas con sprites personalizados, niveles y efectos de sonido.',
      image: '',
      emoji: '🎮',
      gradient: 'linear-gradient(135deg, #e53935 0%, #ff7043 100%)',
      tags: ['Scratch 3.0', 'Diseño', 'Sprites'],
      hasVideo: false,
      hasPDF: true,
      date: '2025-02',
      course: 'Nivel 2 · PEP 6-7'
    },
    {
      id: 'estacion-meteorologica',
      title: 'Estación Meteorológica IoT',
      category: 'arduino',
      description: 'Sensor de temperatura, humedad y presión conectado a internet con ESP32. Datos en tiempo real en un dashboard web propio.',
      image: '',
      emoji: '🌡️',
      gradient: 'linear-gradient(135deg, #2e7d32 0%, #66bb6a 100%)',
      tags: ['Arduino', 'ESP32', 'IoT', 'HTML/CSS'],
      hasVideo: true,
      hasPDF: true,
      date: '2025-04',
      course: 'Nivel 4 · PAI 12-16'
    },
    {
      id: 'clasificador-ia',
      title: 'Clasificador de Imágenes con IA',
      category: 'ia',
      description: 'Entrenamos un modelo de Machine Learning con Teachable Machine y lo integramos en una web para clasificar residuos reciclables.',
      image: '',
      emoji: '🧠',
      gradient: 'linear-gradient(135deg, #ad1457 0%, #f06292 100%)',
      tags: ['ML', 'Teachable Machine', 'Python', 'TensorFlow'],
      hasVideo: true,
      hasPDF: false,
      date: '2025-05',
      course: 'Nivel 4 · PAI 12-16'
    },
    {
      id: 'portfolio-web',
      title: 'Portfolio Web Personal',
      category: 'web',
      description: 'Cada alumno crea su propio portfolio web con HTML, CSS y JavaScript. Diseño responsive y despliegue en GitHub Pages.',
      image: '',
      emoji: '🌐',
      gradient: 'linear-gradient(135deg, #4527a0 0%, #7c4dff 100%)',
      tags: ['HTML5', 'CSS3', 'JS', 'GitHub Pages'],
      hasVideo: false,
      hasPDF: true,
      date: '2025-06',
      course: 'Nivel 4 · PAI 12-16'
    },
    {
      id: 'serpiente-python',
      title: 'Snake en Python',
      category: 'python',
      description: 'Recreación del clásico juego Snake usando Python y Pygame. Programación orientada a objetos, bucles y manejo de eventos.',
      image: '',
      emoji: '🐍',
      gradient: 'linear-gradient(135deg, #f57f17 0%, #ffd600 100%)',
      tags: ['Python', 'Pygame', 'OOP'],
      hasVideo: false,
      hasPDF: false,
      date: '2025-03',
      course: 'Nivel 4 · PAI 12-16'
    }
  ];

  allVideos = [
    { id: 'v1', youtubeId: 'dQw4w9WgXcQ', title: 'Robot Seguidor de Línea en Competición', description: 'Demostración final del robot en el circuito de pruebas.' },
    { id: 'v2', youtubeId: 'ScMzIvxBSi4', title: 'Estación Meteorológica en Acción', description: 'Presentación del proyecto IoT ante las familias.' },
    { id: 'v3', youtubeId: 'ysz5S6PUM-U', title: 'Demo Clasificador IA — Reciclaje', description: 'El modelo de Machine Learning distinguiendo residuos en tiempo real.' }
  ];

  allImages = [
    { id: 'i1', src: 'img/img1.jpg', alt: 'Taller de robótica' },
    { id: 'i2', src: 'img/img2.jpg', alt: 'Programación Scratch' },
    { id: 'i3', src: 'img/img3.jpg', alt: 'Construcción robot' },
    { id: 'i4', src: 'img/img4.jpg', alt: 'Presentación proyectos' },
    { id: 'i5', src: 'img/img5.jpg', alt: 'Arduino lab' },
    { id: 'i6', src: 'img/img6.jpg', alt: 'Equipo trabajo' }
  ];

  allPDFs = [
    { id: 'p1', name: 'Guía del Proyecto Robot Seguidor.pdf', url: 'media/pdfs/guia-robot-seguidor.pdf', size: '1.2 MB', description: 'Documentación completa del proyecto de robótica.' },
    { id: 'p2', name: 'Dossier Estación Meteorológica IoT.pdf', url: 'media/pdfs/dossier-iot.pdf', size: '3.4 MB', description: 'Memoria técnica del proyecto IoT con ESP32.' },
    { id: 'p3', name: 'Itinerario Formativo 2026-2027.pdf', url: 'media/pdfs/itinerario-formativo.pdf', size: '0.8 MB', description: 'Programa oficial de la actividad extraescolar.' }
  ];
}

// ─── FILTERS ────────────────────────────────────────────────────────────────
function initFilters() {
  document.querySelectorAll('#filter-bar .filter-btn').forEach(btn => {
    btn.addEventListener('click', () => {
      document.querySelectorAll('#filter-bar .filter-btn').forEach(b => b.classList.remove('active'));
      btn.classList.add('active');
      activeFilter = btn.dataset.filter;
      renderProjects();
    });
  });
}

// ─── MEDIA TABS ─────────────────────────────────────────────────────────────
function initMediaTabs() {
  document.querySelectorAll('#media-tabs .media-tab-btn').forEach(btn => {
    btn.addEventListener('click', () => {
      document.querySelectorAll('#media-tabs .media-tab-btn').forEach(b => b.classList.remove('active'));
      document.querySelectorAll('.media-panel').forEach(p => p.classList.add('hidden'));
      btn.classList.add('active');
      document.getElementById('panel-' + btn.dataset.tab).classList.remove('hidden');
    });
  });
}

// ─── RENDER ALL ─────────────────────────────────────────────────────────────
function renderAll() {
  renderProjects();
  renderVideos();
  renderGallery();
  renderPDFs();
}

// ─── RENDER PROJECTS ────────────────────────────────────────────────────────
function renderProjects() {
  const grid  = document.getElementById('projects-grid');
  const empty = document.getElementById('projects-empty');
  const filtered = activeFilter === 'all'
    ? allProjects
    : allProjects.filter(p => p.category === activeFilter);

  grid.innerHTML = '';

  if (!filtered.length) {
    grid.classList.add('hidden');
    empty.classList.remove('hidden');
    return;
  }
  grid.classList.remove('hidden');
  empty.classList.add('hidden');

  filtered.forEach(p => {
    const card = document.createElement('div');
    card.className = 'proj-card';
    card.innerHTML = `
      ${p.image
        ? `<img src="${p.image}" alt="${p.title}" class="proj-thumb" loading="lazy" onerror="this.style.display='none';this.nextElementSibling.style.display='flex'">`
        : ''}
      <div class="proj-thumb-placeholder" style="background:${p.gradient || 'linear-gradient(135deg,#111c2d,#1f2a3c)'}; ${p.image ? 'display:none' : ''}">
        ${p.emoji || '🔧'}
      </div>
      <div class="proj-body">
        <span class="proj-cat">${categoryLabel(p.category)}</span>
        <div class="proj-title">${p.title}</div>
        <div class="proj-desc">${p.description}</div>
        ${p.tags?.length ? `<div class="proj-tags">${p.tags.map(t => `<span class="proj-tag">${t}</span>`).join('')}</div>` : ''}
        <div class="proj-icons">
          ${p.hasVideo ? `<span class="proj-icon-badge"><span class="material-symbols-outlined">smart_display</span> Vídeo</span>` : ''}
          ${p.hasPDF   ? `<span class="proj-icon-badge"><span class="material-symbols-outlined">picture_as_pdf</span> PDF</span>` : ''}
          ${p.course   ? `<span class="proj-icon-badge" style="margin-left:auto;font-size:0.68rem;color:#414754">${p.course}</span>` : ''}
        </div>
      </div>
    `;
    grid.appendChild(card);
  });
}

function categoryLabel(cat) {
  const map = { robotica:'Robótica', scratch:'Scratch', arduino:'Arduino', python:'Python', ia:'Inteligencia Artificial', web:'Desarrollo Web' };
  return map[cat] || cat;
}

// ─── RENDER VIDEOS ──────────────────────────────────────────────────────────
function renderVideos() {
  const grid  = document.getElementById('videos-grid');
  const empty = document.getElementById('videos-empty');
  if (!allVideos.length) { grid.classList.add('hidden'); empty.classList.remove('hidden'); return; }

  grid.classList.remove('hidden');
  empty.classList.add('hidden');
  grid.innerHTML = '';

  allVideos.forEach(v => {
    const embedId = extractYoutubeId(v.youtubeId || v.url || '');
    const card = document.createElement('div');
    card.className = 'video-card';
    card.innerHTML = `
      <div class="video-wrapper">
        <iframe
          src="${YOUTUBE_NOCOOKIE}${embedId}?rel=0&modestbranding=1"
          title="${v.title}"
          allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
          allowfullscreen
          loading="lazy">
        </iframe>
      </div>
      <div class="video-info">
        <div class="video-title">${v.title}</div>
        ${v.description ? `<div class="video-desc">${v.description}</div>` : ''}
      </div>
    `;
    grid.appendChild(card);
  });
}

function extractYoutubeId(str) {
  // Accepts raw ID, full URL, or youtu.be short URL
  const patterns = [
    /(?:youtube\.com\/watch\?v=|youtu\.be\/|youtube\.com\/embed\/)([a-zA-Z0-9_-]{11})/,
    /^([a-zA-Z0-9_-]{11})$/
  ];
  for (const p of patterns) {
    const m = str.match(p);
    if (m) return m[1];
  }
  return str;
}

// ─── RENDER GALLERY ─────────────────────────────────────────────────────────
function renderGallery() {
  const grid  = document.getElementById('gallery-grid');
  const empty = document.getElementById('gallery-empty');
  if (!allImages.length) { grid.classList.add('hidden'); empty.classList.remove('hidden'); return; }

  grid.classList.remove('hidden');
  empty.classList.add('hidden');
  grid.innerHTML = '';

  allImages.forEach(img => {
    const item = document.createElement('div');
    item.className = 'gallery-item';
    item.onclick = () => openLightbox(img.src, img.alt);
    item.innerHTML = `<img src="${img.src}" alt="${img.alt}" loading="lazy" onerror="this.closest('.gallery-item').style.display='none'">`;
    grid.appendChild(item);
  });
}

// ─── RENDER PDFs ────────────────────────────────────────────────────────────
function renderPDFs() {
  const list  = document.getElementById('pdfs-list');
  const empty = document.getElementById('pdfs-empty');
  if (!allPDFs.length) { list.classList.add('hidden'); empty.classList.remove('hidden'); return; }

  list.classList.remove('hidden');
  empty.classList.add('hidden');
  list.innerHTML = '';

  allPDFs.forEach(pdf => {
    const card = document.createElement('a');
    card.className = 'pdf-card';
    card.href = pdf.url;
    card.target = '_blank';
    card.rel = 'noopener noreferrer';
    card.innerHTML = `
      <div class="pdf-icon"><span class="material-symbols-outlined" style="font-variation-settings:'FILL' 1">picture_as_pdf</span></div>
      <div class="pdf-meta">
        <div class="pdf-name">${pdf.name}</div>
        <div class="pdf-size">${pdf.description || ''} ${pdf.size ? '· ' + pdf.size : ''}</div>
      </div>
      <div class="pdf-dl"><span class="material-symbols-outlined">download</span></div>
    `;
    list.appendChild(card);
  });
}

// ─── STATS ──────────────────────────────────────────────────────────────────
function updateStats() {
  const animCount = (el, target) => {
    if (!el) return;
    let n = 0;
    const step = Math.max(1, Math.floor(target / 30));
    const t = setInterval(() => {
      n = Math.min(n + step, target);
      el.textContent = n;
      if (n >= target) clearInterval(t);
    }, 40);
  };
  animCount(document.getElementById('stat-proyectos'), allProjects.length);
  animCount(document.getElementById('stat-videos'),    allVideos.length);
  animCount(document.getElementById('stat-fotos'),     allImages.length);
}

// ─── LIGHTBOX ───────────────────────────────────────────────────────────────
function initLightbox() {
  document.getElementById('lightbox').addEventListener('click', e => {
    if (e.target.id === 'lightbox') closeLightbox();
  });
  document.addEventListener('keydown', e => {
    if (e.key === 'Escape') closeLightbox();
  });
}

function openLightbox(src, alt) {
  const lb = document.getElementById('lightbox');
  document.getElementById('lb-img').src = src;
  document.getElementById('lb-img').alt = alt || '';
  lb.classList.add('open');
  document.body.style.overflow = 'hidden';
}

function closeLightbox() {
  document.getElementById('lightbox').classList.remove('open');
  document.body.style.overflow = '';
}
